<script>
    // 这个方法返回一个新的promise对象，
    // 该promise对象在iterable参数对象里所有的promise对象都成功的时候才会触发成功，
    // 一旦有任何一个iterable里面的promise对象失败则立即触发该promise对象的失败。
    // 这个新的promise对象在触发成功状态以后，会把一个包含iterable里所有promise返回值的数组作为成功回调的返回值，
    // 顺序跟iterable的顺序保持一致；
    const p1 = () => {
        return new Promise((resolve, reject) => {
            setTimeout(() => {
                resolve(1)
            }, 1000)
        })
    }
    const p2 = () => {
        return new Promise((resolve, reject) => {
            setTimeout(() => {
                resolve(1)
            }, 2000)
        })
    }
    const p3 = () => {
        return new Promise((resolve, reject) => {
            setTimeout(() => {
                resolve(1)
            }, 3000)
        })
    }
    Promise.myAll = function(promises) {
        // 什么时候结束？当 .then 调用 的时候 一个 promise 就成功了
        return new Promise((resolve,reject) => {
            let count = 0; // 到底完成了几个
            let res = [];
            promises.forEach((pro, i) => {
                pro.then((r) =>{
                    res[i] = r // 不用 push unshift 怕造成 稀疏数组
                    count++;
                    if (count === promises.length) {
                        resolve(res)
                    }
                }).catch(reject)
            })
        })
    }
    Promise.myAll([p1(), p2(), p3()]) // 接受多个 Promise 返回一个 Promise
    .then(console.log)
    .catch(res => {
            console.log('err');
        })

</script>